version: '3.8'

services:
  portfolio-explainer-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - PORT=5001
    volumes:
      - .:/app
      - /app/__pycache__
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    command: ["python", "app.py"]
